### ISSUE TITLE
I need of assistance with adding to cart

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/P5-Web-Dev-Kanap#3]
@AccessiT3ch - Hey Hey Conor!

So I started working on the add to cart code.  I know I have a lot to go, but I want to make sure I get the first part of the cart working first.  The below code snippet creates an empty cart array, creates an item object, and adds item to the cart on click.  Now,  am able to add one item to the cart, but not another and I know it has something to with the if statement.  I think its because I am comparing one thing to itself causing that statement to always be true.  I just don't know how to fix it or what other values I could use to get this block of code to work.  Any assistance you can provide would be greatly appreciated!
https://github.com/mwhite192/P5-Web-Dev-Kanap/blob/f46b5369ad8ad5e8033826f6c67ae2771d15b60d/front/js/product.js#L38-L58

**Comment by AccessiT3ch** [comment]
Hey @mwhite192 I think you're right that the condition in the if statement is always returning true. Part of the issue is that you're comparing two objects with the same name (defined at different scopes), so choosing something more specific (or at least different) than `item` will be a helpful start.

The other thing is that you're not getting the information from the DOM for quantity and color of the clicked product before comparing it. I think if you simply move your item definition (on line 42) into the event listener and set the color and quantity before the if statement, you will have something to actually compare. Moving the `item` definition into the scope will help reduce the risk of mutating the items in your array (I'll try to outline this phenomenon next).

**Comment by AccessiT3ch** [comment]
## Mutation Station
Mutation comes into play when we are referencing a single `Object` or `Array` that saved to memory in multiple places and then changing that initial data. Usually, the browser will try to save memory so it will often save new variables as references of the original, and when that original data changes (aka mutates), so too do the references.

```js
const foo = { id: 'bar' };
const arr = [];

arr.push(foo);  // a reference of foo is pushed
// expected: [{ id: 'foo' }]
// actual: [{ id: 'foo' }]

foo.id = 'zip'; // original object of foo is mutated
arr.push(foo);  // a reference of foo is pushed
// expected: [{ id: 'foo' }, { id: 'zip' }] 
// actual:  [{ id: 'zip' }, { id: 'zip' }]
```

## Scope and the Trash Collector
In the case above, `foo` will never be removed from memory because it's declared at the root scope of the document (and then referenced a bunch). Declaring a variable within a scope is one way to help the Trash Collector free up space (because after the block of code within curly brackets finishes running, memory will try to be freed up), or at least avoid mutation for the most part.

```js
// Mutating!
const arr = [];
const foo = { id: 'bar' };
function updateArray(id) {
  foo.id = id;
  arr.push(foo)
}
updateArray('zip'); // => [{ id: 'zip' }]
updateArray('zap'); // => [{ id: 'zap' }, { id: 'zap' }]

// Not mutating
const arr = [];
function updateArray(id) {
  const foo = { id: id}; // this get redeclared every time the function is called, breaking any previous reference
  arr.push(foo) // still passing a reference of foo, but "foo" will be redeclared, breaking this reference
}
```

## Spreads vs Object.assign() and Array.concat()
Luckily, we have ways to easily use new copies of data instead of references, which not only protects us from mutation but also allows the Trash Collector to reallocate memory from unreferenced and descoped data. The original way to make a new object was use Object.assign() and Array.concat[], and now we have spreads!

```js
// original object that never gets mutated or referenced to another variable
const foo = { id: 'bar', color: 'red', quantity: 1 }

// Object.assign can take one or more parameters of object to merge
const newFoo = Object.assign(foo); // =>  { id: 'bar', color: 'red', quantity: 1 }
const zip = Object.assign(foo, { id: 'zip' }); // =>  { id: 'zip', color: 'red', quantity: 1 }

// Using Spreads we can do the same thing with fewer characters
const newFoo2 = { ...foo };  // =>  { id: 'bar', color: 'red', quantity: 1 }
const zip2 = { ...foo, id: 'zip' }; // =>  { id: 'zip', color: 'red', quantity: 1 }

// original arrays that won't be mutated or referenced
const chairColors = ['red', 'blue', 'green'];
const couchColors = ['orange', 'teal'];

// concat is a function for joining arrays together, it also works on strings
const newChairColors = [].concat(chairColors); // => ['red', 'blue', 'green']
const allColors = [].concat(chairColors, couchColors) // => ['red', 'blue', 'green', 'orange', 'teal']

// spreads for arrays work very similar to object spreads
const colors = [ ...chairColors, ...couchColors]; // =>  ['red', 'blue', 'green', 'orange', 'teal']
const evenMoreColors = [...colors, 'gold', 'sparkles', 'rainbow']; // => ['red', 'blue', 'green', 'orange', 'teal', 'gold', 'sparkles', 'rainbow']



```

**Comment by mwhite192** [comment]
@AccessiT3ch - Thank you so much for this information Conor!  I understand what mutating is now because that was happening with the initial code snippet.  I was able to eliminate the mutation by creating a function.  I do have one more question though.  I just want to make sure my thought process is correct.  So in my function would I then create a reference object and then a copy of that object using spreads, update the color key for the copied object, and then compare the two values in a If statement?

**Comment by AccessiT3ch** [comment]
>  So in my function would I then create a reference object and then a copy of that object using spreads

Basically yes! In different contexts it may make sense to implement this in different ways, this function could also simply return a new object without ever naming it. These three examples will behave pretty much identically:
```js
function myFunc (id) {
  const foo = { id: id };
  // ... some functionality to get color an quantity
  // return a copy of foo while declaring new data on it
  return {
    ...foo,
    color: color,
    quantity: quantity
  }; 
}

function myFunc (id) {
  const foo = { id: id };
  // ... some functionality to get color an quantity
  foo.color = color;
  foo.quantity = quantity;

  // since foo is scoped in function, we don't have to spread a copy of it
  return foo; 
}

function myFunc (id) {
  // ... some functionality to get color an quantity
  // we also don't have to declare foo, we can just return an object
  return {
    id: id,
    color: color,
    quantity: quantity
  };
}
```

**Comment by AccessiT3ch** [comment]
> and then compare the two values in a If statement?

Close! Since you're comparing multiple properties across multiple items in an array, you'll have to iterate through the array to check each one, and if there is a match do a certain thing. Again, there's lots of different ways to implement this, including what you're doing with `Array.some()`! Some simple / common ways this functionality could look: 

```js
const productId = '...'
const selectedItem = myFunc(productId); // { id: '...', color: 'red, quantity: 1 }
const hasMatchingItem = items.some((thisItem) => {
  if (thisItem.id === selectedItem.id && thisItem.color === selectedItem.id) {
    return true;
  } else {
    return false;
  }
});
if (hasMatchingItem) {
  // update existing item in the cart
} else {
  // push the new item to the cart
}
```
Note: `Array.some()` returns a `true` or `false` value, which certainly works, there is also `Array.find()` which will return the actual matching item or `null` which can be used in your if statement the exact same way.

An advantage of using find over some in this scenario is that you are essentially performing both pieces of logic (knowing if there's a match and getting the match) at the same time, so your script only iterates over the array once instead of twice!

`Array.filter()` is also very common and very useful!

**Comment by mwhite192** [comment]
@AccessiT3ch  - thanks Conor for this!  I will play around with this one some more.  We might have to peer program this one because  I understand, but I am still a little confused.  I have to admit this is really tough.  From thinking about how to code should flow to writing it is not easy.  I am trying not to get too much guidance, but that the complexity of this language is making that a little difficult.
